spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #          url: jdbc:mysql://localhost:3306/webfounder
    url: jdbc:mysql://webfounder.cdcmskceihxl.ap-northeast-2.rds.amazonaws.com:3306/webfounder?serverTimezone=Asia/Seoul
    username: webfounder_root
    password: webfounder1234

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  spring:
    datasource:
      hikari:
        maximum-pool-size: 10
        minimum-idle: 2
        idle-timeout: 30000
        max-lifetime: 1800000
        connection-timeout: 30000
    jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
    jackson:
      time-zone: Asia/Seoul

logging:
  file:
    path: /home/ubuntu/
  level:
    org.hibernate.SQL: debug




secret:
  jwt: aBcDeFgHiJkLmNoPqRsTuVwXyZ0123456789AbCdEfGhIjKlMnOpQrStUvWxYz



